# Read the Docs configuration file for MkDocs projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    # latest 3.x version available on Read the Docs
    python: "3"

mkdocs:
  configuration: docs/mkdocs.yml

python:
  install:
  - requirements: docs/requirements.txt
